services:
  pleximagee-ink:
    build: .
    container_name: pleximagee-ink
    init: true
    ports:
      - "8787:8787"
    environment:
      PLEXINK_CONFIG_FILE: /config/settings.env
      PLEXINK_OUTPUT_DIR:  /output
      PLEXINK_LOGS_DIR:    /logs
    volumes:
      - ./config:/config
      - ./data/output:/output
      - ./logs:/logs
    restart: unless-stopped
